name: Build Release

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🦀 Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: 🛠️ Install cargo-bundle
        run: cargo install cargo-bundle

      - name: 🚀 Build and Bundle for macOS
        run: |
          # 1. Compilation de l'interface graphique
          cargo build --release --bin p-rust-ui
          
          # 2. Création du bundle .app pour le daemon
          cargo bundle --release --bin p-rust
          
          # 3. Copie de l'interface graphique dans le paquet p-rust.app généré
          cp target/release/p-rust-ui "target/release/bundle/osx/p-rust.app/Contents/MacOS/"

      - name: 🗜️ Zip the Application
        run: |
          cd target/release/bundle/osx/
          zip -r PasteClone-macOS.zip "p-rust.app"

      - name: 📤 Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p-rust-macos-app
          path: target/release/bundle/osx/PasteClone-macOS.zip